# Environment
#-------------------------------------------------------------------------------
DEVMODE: False               # Spoof hardware interfaces for development
DEBUG: False                 # Extra logging output
CONFIG_DIR: '~/.hydropi'
DAEMON_HTTP_PORT: 2021

# Hardware pins (BCM)
#-------------------------------------------------------------------------------

# Inputs
PIN_TEMPERATURE: 2
PIN_DEPTH_TRIG: 4
PIN_DEPTH_ECHO: 5

# MCP3008 ADC chip
PIN_MISO: 19  # Din
PIN_MOSI: 20  # Dout
PIN_CLK: 21   # CLK
PIN_CS: 26    # Channel select

# MCP3008 channels 0-7
CHANNEL_PH: 0
CHANNEL_EC: 1
CHANNEL_PRESSURE: 2

# Output mapping
# <Relay channel>: <BCM pin>
# 1: 14
# 2: 15
# 3: 18
# 4: 23
# 5: 24
# 6: 25
# 7: 7
# 8: 1

PIN_PRESSURE_PUMP: 14        # Ch. 1
PIN_MIST_VALVE: 15           # Ch. 2
PIN_NUTRIENT_PUMP: 18        # Ch. 3
PIN_PH_DOWN_PUMP: 23         # Ch. 4
PIN_MIX_PUMP: 24             # Ch. 5
PIN_WATER_VALVE: 25          # Ch. 6
SPARE_RELAY_PIN_A: 7         # Ch. 7
SPARE_RELAY_PIN_B: 1         # Ch. 8

# Parameters
#-------------------------------------------------------------------------------

# General monitoring
QUIET_TIME_START: "20:00"        # HH:MM
QUIET_TIME_END: "07:00"          # HH:MM
SWEEP_CYCLE_MINUTES: 10
MEDIAN_INTERVAL_SECONDS: 0.01    # Pause in seconds between samples

# Misting
MIST_CYCLE_MINUTES: 5
MIST_CYCLE_NIGHT_MINUTES: 20     # Reduce misting frequency during quiet time
MIST_DURATION_SECONDS: 3

# Pressure monitoring
MIN_PRESSURE_PSI: 100                 # Optimal range to maintain
MAX_PRESSURE_PSI: 130
PRESSURE_REFILL_DURATION_SECONDS: 60  # This should be 75% of the time taken to refill from min -> max (0.375psi per second)

# PH monitoring
PH_MIN: 5.8
PH_MAX: 6.2
PH_DANGER: 0.8

# EC monitoring
EC_MIN: 1.8
EC_MAX: 2.2
EC_ADDITION_SECONDS: 2           # Nutrients dose between mix + measure

# Mixer pump - mix nutrient and pH additions into reservoir
MIX_PUMP_SECONDS: 300
MIX_ADDITION_DELAY_SECONDS: 10

# Reservoir water level monitoring
TANK_HEIGHT_MM: 452              # Total distance between head sensor and tank bottom (e.g. 225mm)
DEPTH_MAX_MM: 400                # Depth units when full (e.g. 200mm)
VOLUME_TARGET_L: 12              # Volume to maintain (litres)
VOLUME_TOLERANCE: 0.05           # Tolerated percent difference (of target)
WATER_ADDITION_SECONDS: 10
WATER_MAX_ADDITION_SECONDS: 60

# Database connection
#-------------------------------------------------------------------------------

# Read live config from database (will override default config in this file)

# DATABASE:
#   - SQLITE_PATH: "db.sqlite"
#   - CONFIG_TABLE_NAME: "dash_config"
#   - CONFIG_KEY_FIELD: "key"
#   - CONFIG_VALUE_FIELD: "value"
#   - DATALOG_TABLE_NAME: "dash_history"
