# Generated by Django 3.2 on 2022-01-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20211230_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='depth_mm',
            new_name='depth_l',
        ),
    ]
