# Generated by Django 3.2 on 2022-01-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_rename_depth_mm_history_depth_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='type',
            field=models.CharField(default='str', max_length=5),
            preserve_default=False,
        ),
    ]
