# Generated by Django 3.2 on 2022-01-26 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_config_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
