# Generated by Django 3.2 on 2022-01-27 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_history_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='depth_l',
        ),
        migrations.AddField(
            model_name='history',
            name='volume_l',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
