# Generated by Django 3.2 on 2022-02-01 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_auto_20220127_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='ec',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
